In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [3]:
X,y=make_classification(n_samples=10000,n_features=10,n_informative=3)

In [4]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [30]:
X_test.shape

(2000, 10)

In [5]:
dt=DecisionTreeClassifier(random_state=42)
dt.fit(X_train,y_train)
y_pred=dt.predict(X_test)

print("Decision Tree accuracy ",accuracy_score(y_test,y_pred))


Decision Tree accuracy  0.893


Bagging

In [9]:
bag=BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    random_state=42
)

In [10]:
bag.fit(X_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), max_samples=0.25,
                  n_estimators=500, random_state=42)

In [11]:
y_pred=bag.predict(X_test)

In [12]:
accuracy_score(y_test,y_pred)

0.922

In [13]:
bag.estimators_samples_  #signifies which rows are assigned to which model

[array([2523, 3113, 7114, ..., 4291, 4472, 3620], dtype=int32),
 array([4782,  663, 7155, ..., 5963,  495, 1767], dtype=int32),
 array([5462, 6574, 4896, ..., 3979, 7827,   37], dtype=int32),
 array([2848, 2629, 1591, ..., 7723, 1314, 1565], dtype=int32),
 array([3821, 6494, 1606, ..., 5686, 7870, 2558], dtype=int32),
 array([2261, 7922, 3649, ..., 4478, 6286, 6943], dtype=int32),
 array([ 652, 1676, 2291, ..., 2723, 7007, 6344], dtype=int32),
 array([2478, 4107, 1958, ..., 7979, 5695, 7854], dtype=int32),
 array([5800, 3548, 6540, ..., 3899,  831,   55], dtype=int32),
 array([5256, 7181, 3409, ..., 5286, 7535, 1335], dtype=int32),
 array([2675, 2834, 3817, ..., 1726, 2323, 7642], dtype=int32),
 array([3236, 7607, 4600, ...,  445, 7501, 6604], dtype=int32),
 array([4563, 4137, 6298, ..., 6611, 3023, 5529], dtype=int32),
 array([2816, 5343, 5817, ..., 3197, 2917, 5775], dtype=int32),
 array([2448, 2733, 5480, ...,  747, 5842,   69], dtype=int32),
 array([4248, 3828, 4630, ..., 1284, 254

In [15]:
bag.estimators_features_  #whichfeatures are assigned to which model here all feature to all model

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),


Bagging with SVM

In [16]:
bag=BaggingClassifier(
    estimator=SVC(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    random_state=42
)

In [17]:
bag.fit(X_train,y_train)

BaggingClassifier(estimator=SVC(), max_samples=0.25, n_estimators=500,
                  random_state=42)

In [18]:
y_pred=bag.predict(X_test)

In [19]:
accuracy_score(y_test,y_pred)

0.8565

Pasting

In [24]:
bag=BaggingClassifier(
    estimator=DecisionTreeClassifier(),  #also try changing to SVC
    n_estimators=500,
    max_samples=0.25,
    bootstrap=False,
    random_state=42,
    verbose=1,
    n_jobs=-1
)

In [25]:
bag.fit(X_train,y_train)
y_pred=bag.predict(X_test)
accuracy_score(y_test,y_pred)

[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   2 out of  16 | elapsed:    1.5s remaining:   11.4s
[Parallel(n_jobs=16)]: Done  16 out of  16 | elapsed:    1.6s finished
[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   2 out of  16 | elapsed:    0.0s remaining:    0.1s
[Parallel(n_jobs=16)]: Done  16 out of  16 | elapsed:    0.0s finished


0.926

Random Subspaces

In [26]:
bag=BaggingClassifier(
    estimator=DecisionTreeClassifier(),  #also try changing to SVC
    n_estimators=500,
    max_samples=1.0,
    bootstrap=False,
    random_state=42,
    max_features=0.5,
    bootstrap_features=True,
    verbose=1,
    n_jobs=-1
)

In [27]:
bag.fit(X_train,y_train)
y_pred=bag.predict(X_test)
accuracy_score(y_test,y_pred)

[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   2 out of  16 | elapsed:    4.7s remaining:   33.5s
[Parallel(n_jobs=16)]: Done  16 out of  16 | elapsed:    5.3s finished
[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   2 out of  16 | elapsed:    0.0s remaining:    0.9s
[Parallel(n_jobs=16)]: Done  16 out of  16 | elapsed:    0.5s finished


0.906

In [31]:
bag.estimators_features_[0].shape

(5,)

Random Patches

In [32]:
bag=BaggingClassifier(
    estimator=DecisionTreeClassifier(),  #also try changing to SVC
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    random_state=42,
    max_features=0.5,
    bootstrap_features=True,
    verbose=1,
    n_jobs=-1
)

In [33]:
bag.fit(X_train,y_train)
y_pred=bag.predict(X_test)
accuracy_score(y_test,y_pred)

[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   2 out of  16 | elapsed:    1.0s remaining:    7.7s
[Parallel(n_jobs=16)]: Done  16 out of  16 | elapsed:    1.1s finished
[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   2 out of  16 | elapsed:    0.0s remaining:    0.2s
[Parallel(n_jobs=16)]: Done  16 out of  16 | elapsed:    0.1s finished


0.898

OOB Score

In [34]:
bag=BaggingClassifier(
    estimator=DecisionTreeClassifier(),  #also try changing to SVC
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    random_state=42,
    max_features=0.5,
    bootstrap_features=True,
    verbose=1,
    oob_score=True,
    n_jobs=-1
)

In [35]:
bag.fit(X_train,y_train)
y_pred=bag.predict(X_test)
accuracy_score(y_test,y_pred)

[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   2 out of  16 | elapsed:    1.0s remaining:    7.5s
[Parallel(n_jobs=16)]: Done  16 out of  16 | elapsed:    1.2s finished
[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   2 out of  16 | elapsed:    0.0s remaining:    0.2s
[Parallel(n_jobs=16)]: Done  16 out of  16 | elapsed:    0.1s finished


0.898

In [36]:
bag.oob_score_

0.899875

Applying GridSearchCV

In [37]:
from sklearn.model_selection import GridSearchCV

In [38]:
parameters={
    'n_estimators':[50,100,500],
    'max_samples':[0.1,0.4,0.7,1.0],
    'bootstrap':[True,False],
    'max_features':[0.1,0.4,0.7,1.0]
}

In [39]:
mod=GridSearchCV(BaggingClassifier(),parameters,cv=5)

In [41]:
mod.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=BaggingClassifier(),
             param_grid={'bootstrap': [True, False],
                         'max_features': [0.1, 0.4, 0.7, 1.0],
                         'max_samples': [0.1, 0.4, 0.7, 1.0],
                         'n_estimators': [50, 100, 500]})

In [ ]:
mod.best_params_